# Generated by Django 5.2.6 on 2025-09-26 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_options_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_capacity', models.IntegerField(default=50, help_text='Maximum number of guests per day')),
                ('max_time_slot_capacity', models.IntegerField(default=20, help_text='Maximum guests per 2-hour time slot')),
                ('booking_advance_days', models.IntegerField(default=30, help_text='How many days in advance bookings are allowed')),
            ],
            options={
                'verbose_name': 'Restaurant Configuration',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'booking_date')},
        ),
    ]
