# Generated by Django 5.2.6 on 2025-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantconfig_booking_created_at_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the dish', null=True, upload_to='menu_images/'),
        ),
    ]
